all:  matching

# Matching
# You are given three sets of image patches, corresponding to portions of
# a normalized grayscale image (i.e. all values are from 0.0-1.0, as opposed to
# 0-255). For the reference patch, which is the closest candidate patch? (For
# your definition of closeness).
matching:	src/matching.cc
					g++ src/matching.cc -std=c++14 -o matching


clean:
	rm matching
