all:  modeling

# Modeling
# You are given a list of input data points corresponding to
# a independent/depenent variable pair. Estimate the relationship between the
# dependent and independent variable with a polynomial model of your choice, and
# report how well that model fits (the residual error).
modeling:	src/modeling.cc
					g++ src/modeling.cc -std=c++14 -o modeling


clean:
	rm modeling
