all:  strings

# Strings
# Write a program that takes a path to a file containing a list of words (e.g.
# "/usr/share/dict) and count the number of palindromic words in the list.
# A palindromic word (for this problem) is a word that reads the same in the
# forwards and reverse order, and is case-sensitive (i.e. Z != z). Report total
# count of palindromic words
strings:	src/strings.cc
					g++ src/strings.cc -std=c++14 -o strings


clean:
	rm strings
